-- Convertir les colonnes de texte des communautés en utf8mb4 (emojis 4 octets)

SET @c0 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='communities' AND COLUMN_NAME='name' AND CHARACTER_SET_NAME='utf8');
SET @s0 = IF(@c0>0, 'ALTER TABLE communities MODIFY COLUMN name VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL', 'SELECT 1');
PREPARE st0 FROM @s0;
EXECUTE st0;
DEALLOCATE PREPARE st0;

SET @c1 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='communities' AND COLUMN_NAME='displayName' AND CHARACTER_SET_NAME='utf8');
SET @s1 = IF(@c1>0, 'ALTER TABLE communities MODIFY COLUMN displayName VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL', 'SELECT 1');
PREPARE st1 FROM @s1;
EXECUTE st1;
DEALLOCATE PREPARE st1;

SET @c2 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='communities' AND COLUMN_NAME='description' AND CHARACTER_SET_NAME='utf8');
SET @s2 = IF(@c2>0, 'ALTER TABLE communities MODIFY COLUMN description TEXT CHARACTER SET utf8mb4 DEFAULT NULL', 'SELECT 1');
PREPARE st2 FROM @s2;
EXECUTE st2;
DEALLOCATE PREPARE st2;

SET @c3 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='communities' AND COLUMN_NAME='category' AND CHARACTER_SET_NAME='utf8');
SET @s3 = IF(@c3>0, 'ALTER TABLE communities MODIFY COLUMN category VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL', 'SELECT 1');
PREPARE st3 FROM @s3;
EXECUTE st3;
DEALLOCATE PREPARE st3;

SET @c4 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='communities' AND COLUMN_NAME='rules' AND CHARACTER_SET_NAME='utf8');
SET @s4 = IF(@c4>0, 'ALTER TABLE communities MODIFY COLUMN rules TEXT CHARACTER SET utf8mb4 DEFAULT NULL', 'SELECT 1');
PREPARE st4 FROM @s4;
EXECUTE st4;
DEALLOCATE PREPARE st4;

SET @c5 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='community_posts' AND COLUMN_NAME='title' AND CHARACTER_SET_NAME='utf8');
SET @s5 = IF(@c5>0, 'ALTER TABLE community_posts MODIFY COLUMN title VARCHAR(300) CHARACTER SET utf8mb4 NOT NULL', 'SELECT 1');
PREPARE st5 FROM @s5;
EXECUTE st5;
DEALLOCATE PREPARE st5;

SET @c6 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='community_posts' AND COLUMN_NAME='content' AND CHARACTER_SET_NAME='utf8');
SET @s6 = IF(@c6>0, 'ALTER TABLE community_posts MODIFY COLUMN content TEXT CHARACTER SET utf8mb4 DEFAULT NULL', 'SELECT 1');
PREPARE st6 FROM @s6;
EXECUTE st6;
DEALLOCATE PREPARE st6;

SET @c7 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='community_comments' AND COLUMN_NAME='content' AND CHARACTER_SET_NAME='utf8');
SET @s7 = IF(@c7>0, 'ALTER TABLE community_comments MODIFY COLUMN content TEXT CHARACTER SET utf8mb4 NOT NULL', 'SELECT 1');
PREPARE st7 FROM @s7;
EXECUTE st7;
DEALLOCATE PREPARE st7;

SET @c8 = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='community_bans' AND COLUMN_NAME='reason' AND CHARACTER_SET_NAME='utf8');
SET @s8 = IF(@c8>0, 'ALTER TABLE community_bans MODIFY COLUMN reason TEXT CHARACTER SET utf8mb4 DEFAULT NULL', 'SELECT 1');
PREPARE st8 FROM @s8;
EXECUTE st8;
DEALLOCATE PREPARE st8;
