ALTER TABLE users ADD COLUMN musicProvider VARCHAR(32) DEFAULT NULL;
ALTER TABLE users ADD COLUMN musicUrl TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN musicTitle VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN musicArtist VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN musicThumbnail TEXT DEFAULT NULL;